name: CI
on:
  push:
    branches:
    - main
    - develop
  pull_request:
    - main
    - develop
  workflow_dispatch: {}

jobs:
  test-affected:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: check Linting
      run: ng lint

    - name: run karma tests
      run: ng test:headless

    
    - name: build project
      run: ng build:prod
